[2025-01-30T00:58:39.326+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: embulk_pipeline_csv.load_csv_to_csv manual__2025-01-30T00:58:35.517143+00:00 [queued]>
[2025-01-30T00:58:39.338+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: embulk_pipeline_csv.load_csv_to_csv manual__2025-01-30T00:58:35.517143+00:00 [queued]>
[2025-01-30T00:58:39.338+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-01-30T00:58:39.339+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-01-30T00:58:39.339+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-01-30T00:58:39.355+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): load_csv_to_csv> on 2025-01-30 00:58:35.517143+00:00
[2025-01-30T00:58:39.362+0000] {standard_task_runner.py:55} INFO - Started process 93 to run task
[2025-01-30T00:58:39.365+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'embulk_pipeline_csv', 'load_csv_to_csv', 'manual__2025-01-30T00:58:35.517143+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_csv_dag.py', '--cfg-path', '/tmp/tmpoc19ags2']
[2025-01-30T00:58:39.365+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask load_csv_to_csv
[2025-01-30T00:58:39.483+0000] {task_command.py:376} INFO - Running <TaskInstance: embulk_pipeline_csv.load_csv_to_csv manual__2025-01-30T00:58:35.517143+00:00 [running]> on host 39f1336c6349
[2025-01-30T00:58:39.603+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=embulk_pipeline_csv
AIRFLOW_CTX_TASK_ID=load_csv_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2025-01-30T00:58:35.517143+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-30T00:58:35.517143+00:00
[2025-01-30T00:58:39.604+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-01-30T00:58:39.605+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'java -jar /opt/embulk/embulk-0.9.25.jar run /opt/***/dags/config_load_csv.yml']
[2025-01-30T00:58:39.617+0000] {subprocess.py:86} INFO - Output:
[2025-01-30T00:58:39.619+0000] {subprocess.py:93} INFO - /bin/bash: line 1: java: command not found
[2025-01-30T00:58:39.620+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-01-30T00:58:39.647+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-01-30T00:58:39.651+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=embulk_pipeline_csv, task_id=load_csv_to_csv, execution_date=20250130T005835, start_date=20250130T005839, end_date=20250130T005839
[2025-01-30T00:58:39.669+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task load_csv_to_csv (Bash command failed. The command returned a non-zero exit code 127.; 93)
[2025-01-30T00:58:39.697+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2025-01-30T00:58:39.744+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
